config/routes.rb
Rails.application.routes.draw do

  resources :cfg_opciones_menus do
    collection do
      get 'buscar'
    end
    resources :cfg_operaciones_opciones_menu
  end
  resources :cfg_perfiles_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_operaciones'
      post 'guardar_operacion_opcion'
      post 'guardar_todas_operacion_opcion'
    end
    member do
      get 'asociar_opciones_menu'
      post 'guardar_asociar_opciones_menu'
    end
  end
  resources :cfg_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_sedes_por_empresa'
    end
    member do
      get 'reiniciar_clave'
      post 'guardar_reinicio_clave'
    end 
  end
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'my_devise/registrations'  }
  
  resources :cfg_pacientes
  resources :cfg_items_horarios
  resources :cfg_horarios do
    collection do
      post 'listar_horarios'  
      post 'editar_horarios'    
    end
  end
  resources :cfg_empresas do
    resources :cfg_sedes do
      resources :cfg_consultorios
    end    
  end

  resources :cit_turnos do
    collection do
      post 'buscar_usuario'
      post 'buscar_horarios'
      post 'buscar_agenda'
      post 'buscar_evento'      
      get 'search'
      post 'buscar'
      post 'buscar_prestador'
    end
    resources :cit_citas
  end

  resources :cfg_dias_no_laborales
  resources :citas do
    collection do
      post 'buscar_usuario'
      post 'buscar_agenda'
      post 'buscar_paciente'
      post 'cancelar_cita'
      get 'usuarios'
    end
  end
  root 'bienvenida#index'
  get 'bienvenida/index'
  resources :especialidades
  post '/cfg_empresas/:id/:activo', to: 'cfg_empresas#estatus_empresa', as: 'estatus_empresa'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:id/:activo', to: 'cfg_sedes#estatus_sede', as: 'estatus_sede'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:cfg_sede_id/cfg_consultorios/:id/:activo', to: 'cfg_consultorios#estatus_consultorio', as: 'estatus_consultorio'
  post '/cfg_pacientes/buscar_pacientes', to: 'cfg_pacientes#buscar_pacientes', as: 'buscar_pacientes'
  post '/cfg_pacientes/buscar_paciente', to: 'cfg_pacientes#buscar_paciente', as: 'buscar_paciente'
  # usuarios
  post '/cfg_usuarios/:id/:activo', to: 'cfg_usuarios#estatus_usuario', as: 'estatus_usuario'
  post '/cfg_perfiles_usuarios/:id/:activo', to: 'cfg_perfiles_usuarios#estatus_perfil', as: 'estatus_perfil'
  post '/cfg_opciones_menus/:id/:activo', to: 'cfg_opciones_menus#estatus_opcion', as: 'estatus_opcion'
  post '/cfg_opciones_menu/:cfg_opciones_menu_id/cfg_operaciones_opciones_menu/:id/:activo', to: 'cfg_operaciones_opciones_menu#estatus_operacion', as: 'estatus_operacion' 
  post '/cit_citas/buscar_paciente_cita', to: 'cit_citas#buscar_paciente_cita', as: 'buscar_paciente_cita'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Errores generados por id's o recursos no existentes, entre otros
  get 'errors/not_found'
  get 'errors/internal_server_error'  
  get '*path', to: 'application#routing_error'
  # Obligatoriamente va en el último lugar. Caso contrario, devuelve cualquier request, así no tenga error
  get '*unmatched_route', to: 'errors#not_found'
end

app/controllers/cfg_usuarios_controller.rb
class CfgUsuariosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cfg_usuario, only: [:show, :edit, :update, :estatus_usuario, 
  :reiniciar_clave, :guardar_reinicio_clave] #:destroy,
  
  # GET /cfg_usuarios
  # GET /cfg_usuarios.json
  def index
    query_listar_usuarios
  end

  # GET /cfg_usuarios/1
  # GET /cfg_usuarios/1.json
  def show
  end

  # GET /cfg_usuarios/new
  #def new
  #  @cfg_usuario = CfgUsuario.new
  #end

  # GET /cfg_usuarios/1/edit
  def edit
  end

  # POST /cfg_usuarios
  # POST /cfg_usuarios.json
  #def create
  #end

  # PATCH/PUT /cfg_usuarios/1
  # PATCH/PUT /cfg_usuarios/1.json
  def update
    begin 
      flash[:alert] = ""
      # Guardar los datos en las tablas users y cfg_usuarios  
      CfgUsuario.transaction do
        @cfg_usuario.login_usuario = params[:user][:username]        
        # Actualizar el modelo cfg_usuario 
        if @cfg_usuario.update(cfg_usuario_params)
          # Actualizar el modelo user
          if @user.update(user_params)
            # Actualizar la imagen de la foto en la tabla maestra cfg_imagen
            if !cfg_imagen_params.nil?             
              if @cfg_imagen.nil?
                # Crear la imagen
                @cfg_imagen = CfgImagen.new(cfg_imagen_params)
                @cfg_imagen.save! 
                # Atributo vinculado
                @cfg_usuario.cfg_imagen_id = @cfg_imagen.id 
                @cfg_usuario.save!
              else
                # Actualizar la imagen  
                @cfg_imagen.update_attributes!(cfg_imagen_params)
              end
            end    
            # Actualizar la imagen de la firma en la tabla maestra cfg_imagen
            if !imagen_firma_params.nil?
              if @imagen_firma.nil?
                # Crear la imagen
                @imagen_firma = CfgImagen.new(imagen_firma_params)
                @imagen_firma.save! 
                # Atributo vinculado
                @cfg_usuario.firma_id = @imagen_firma.id  
                @cfg_usuario.save!
              else
                # Actualizar la imagen  
                @imagen_firma.update_attributes!(imagen_firma_params)
              end
            end
            flash[:notice] = "Usuario actualizado satisfactoriamente"
            # Redireccionar al listar usuarios
            redirect_to cfg_usuarios_path
          else
            flash[:alert] = "Error al actualizar el usuario"
            render :edit
          end
        else
          flash[:alert] = "Error al actualizar el usuario"
          render :edit  
        end  
      end  # de la transaccion
    rescue ActiveRecord::RecordInvalid =>  exception
        imprimir_mensajes_excepcion(exception)
          flash[:alert] = "Error al guardar el usuario"
        render :edit
    rescue ActiveRecord::RecordNotUnique => exception
        imprimir_mensajes_excepcion(exception)
        flash[:alert] = "Error al guardar el usuario"
        render :edit
    rescue => exception
        imprimir_mensajes_excepcion(exception)
        flash[:alert] = "Error al guardar el usuario"
        render :edit
      end  
  end

 
  # METODO QUE ACTUALIZA EL ESTATUS DE LA CUENTA DE USUARIO
  def estatus_usuario
    if @cfg_usuario.update(estado_cuenta: !devolver_valor_activo(params[:activo]))
      flash[:notice] = "Estatus de la cuenta de usuario actualizado satisfactoriamente"      
    else
      flash[:alert] = "Estatus de la cuenta de usuario no pudo ser actualizado"  
      # Mostrar junto al mensaje de alert, los errores del modelo
      @cfg_usuario.errors.each do |campo,msg| 
        flash[:alert] = flash[:alert]  + "<BR>"
        flash[:alert] = flash[:alert]  + msg 
      end
    end
    redirect_to cfg_usuarios_url  
  end  

  # Buscar usuarios segun la ventana de criterios de busqueda
  # Y la paginacion, despues de haber filtrado por algun criterio 
  # de busqueda
  def buscar
    # Ejecuta el query
    query_listar_usuarios
    # Si la accion es buscar por los criterios de busqueda, va al js
    # De lo contrario va al index    
    if !params[:commit].nil? and params[:commit].strip == "Buscar"
      render "buscar.js"
    else
      render :index
    end  
  end

  # Método que ejecuta el query segun el perfil de usuario
  # y los criterios de busqueda 
  def query_listar_usuarios    
    # Variables para la condicion y valores del query
    condiciones = []
    argumentos = Hash.new 

    # Perfil Administrador de Empresa, solo 
    # filtrar los usuarios de sus sedes-Empresa
    if session[:usuario_asociado_empresa] == true
      condiciones << 'cfg_empresas.id = :empresa_id'
      argumentos[:empresa_id] = session[:empresa_id]
    end

    # Criterio de busqueda: login 
    unless params[:login].blank?
      condiciones << 'login_usuario = :login_usuario'
      argumentos[:login_usuario] = params[:login]
    end
    # Criterio de busqueda: nombre y apellidos 
    unless params[:nombres_apellidos].blank?
      condiciones << 'compara_ascii(UPPER(primer_nombre))    ILIKE compara_ascii(UPPER(:nombres_apellidos)) OR 
                      compara_ascii(UPPER(segundo_nombre))   ILIKE compara_ascii(UPPER(:nombres_apellidos)) OR 
                      compara_ascii(UPPER(primer_apellido))  ILIKE compara_ascii(UPPER(:nombres_apellidos)) OR 
                      compara_ascii(UPPER(segundo_apellido)) ILIKE compara_ascii(UPPER(:nombres_apellidos))'
      argumentos[:nombres_apellidos] = "%"+params[:nombres_apellidos].strip+"%"
    end
    # Criterio de búsqueda: perfil
    unless params[:perfil_id].blank?
      condiciones << 'cfg_perfiles_usuario_id = :perfil_id'
      argumentos[:perfil_id] = params[:perfil_id]
    end
    # Criterio de búsqueda: tipo de usuario
     unless params[:tipo_usuario_id].blank?
      condiciones << 'tipo_usuario = :tipo_usuario_id'
      argumentos[:tipo_usuario_id] = params[:tipo_usuario_id]
    end
    # Criterio de búsqueda: empresa
     unless params[:empresa_id].blank?
      condiciones << 'cfg_sedes.cfg_empresa_id = :empresa_id'
      argumentos[:empresa_id] = params[:empresa_id]
    end
    # Criterio de búsqueda: sede
     unless params[:sede_id].blank?
      condiciones << 'cfg_sede_id = :sede_id'
      argumentos[:sede_id] = params[:sede_id]
    end
    # Criterio de búsqueda: estatus de la cuenta
     unless params[:estado_cuenta].blank?
      condiciones << 'cfg_usuarios.estado_cuenta = :estado_cuenta'
      argumentos[:estado_cuenta] = params[:estado_cuenta]
    end

    # Query
    @cfg_usuarios = CfgUsuario.select("cfg_usuarios.id, cfg_usuarios.tipo_identificacion, cfg_usuarios.identificacion, cfg_usuarios.tipo_usuario,
      cfg_usuarios.primer_nombre, cfg_usuarios.segundo_nombre, cfg_usuarios.primer_apellido, cfg_usuarios.segundo_apellido,
      cfg_usuarios.estado_cuenta, cfg_empresas.razon_social, cfg_sedes.nombre_sede,
      cfg_usuarios.login_usuario, (cfg_usuarios.primer_nombre || cfg_usuarios.segundo_nombre) AS nombres,
      (cfg_usuarios.primer_apellido || cfg_usuarios.segundo_apellido) AS apellidos, cfg_usuarios.cfg_perfiles_usuario_id,
      UPPER(cfg_perfiles_usuarios.nombre_perfil) AS nombre_perfil, 
      UPPER(cfg_clasif_tipo_usuario.descripcion) AS nombre_tipo_usuario,
      UPPER(cfg_clasif_tipo_identificacion.descripcion) AS descripcion_tipo_identificacion")   
    .joins("INNER JOIN users ON cfg_usuarios.user_id = users.id 
            INNER JOIN cfg_perfiles_usuarios ON cfg_usuarios.cfg_perfiles_usuario_id = cfg_perfiles_usuarios.id
            LEFT JOIN cfg_clasificaciones cfg_clasif_tipo_usuario ON cfg_usuarios.tipo_usuario = cfg_clasif_tipo_usuario.id
            LEFT JOIN cfg_clasificaciones cfg_clasif_tipo_identificacion ON cfg_usuarios.tipo_identificacion = cfg_clasif_tipo_identificacion.id
            LEFT JOIN cfg_sedes ON cfg_usuarios.cfg_sede_id =  cfg_sedes.id
            LEFT JOIN cfg_empresas ON cfg_sedes.cfg_empresa_id = cfg_empresas.id")
    .order('login_usuario').page(params[:page])
    .where(condiciones.join(" AND "),argumentos)
    
  end

  def actualizar_sedes_por_empresa
  end

  # METODO QUE MUESTRA LA PAGINA PARA EL REINICIO DE CLAVE DEL USUARIO
  def reiniciar_clave

  end
  
  # METODO PARA GUARDAR LA NUEVA CLAVE DEL USUARIO
  def guardar_reinicio_clave
    if @user.update(user_params)
      redirect_to cfg_usuarios_path, notice: 'Se reinició la clave del usuario satisfactoriamente'      
    else
      render :reiniciar_clave
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cfg_usuario
      @cfg_usuario  = CfgUsuario.find(params[:id])
      @user = @cfg_usuario.user
      @cfg_imagen   = @cfg_usuario.cfg_imagen
      @imagen_firma = @cfg_usuario.imagen_firma
      # Verificar el acceso al registro, por la empresa
      # asociada al usuario de la sesion
      if session[:usuario_asociado_empresa] == true
        autorizado = @cfg_usuario.autorizado_por_empresa?(session[:empresa_id])
        if autorizado == false
          no_autorizado_registro(@cfg_usuario)
        end
      end  
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cfg_usuario_params
      params.require(:cfg_usuario).permit(:tipo_usuario, :integer, :identificacion, 
        :tipo_identificacion, :login_usuario, :estado_cuenta, :primer_nombre, 
        :segundo_nombre, :primer_apellido, :segundo_apellido, :genero, :cfg_municipio_id, 
        :direccion, :telefono_residencia, :telefono_oficina, :celular, :email, :cargo_actual, 
        :observacion, :cfg_perfiles_usuario_id, :visible, :mostrar_en_historias, :especialidad, 
        :registro_profesional, :personal_atiende, :unidad_funcional, :porcentaje_honorario, 
        :cfg_sede_id )
    end
    def user_params
      # NOTE: Using `strong_parameters` gem
      params[:user].permit(:username, :password, :password_confirmation) if !params[:user].nil?
    end
    # Imagen de la foto  del usuario

app/helpers/cfg_usuarios_helper.rb
module CfgUsuariosHelper
end

app/views/cfg_usuarios/_datos_imagenes.html.erb
  <h4>Imágenes del usuario</h4>
  <hr/>
  <div class="row">
    <div class="col">
      <%= label :cfg_imagen, :imagen, 'Foto', class: "control-label" %>   
    </div>
    <div class="col">
      <%= label :imagen_firma, :imagen, 'Firma', class: "control-label" %>   
    </div>
  </div>
  <div class="row">
    <div class="col">      
      <div class="field">
        <%= file_field :cfg_imagen, :image %>
        &nbsp;
        <%# image_tag @cfg_imagen.image.url(:med) if !@cfg_imagen.nil? %>
        <%= mostrar_imagen(@cfg_imagen).html_safe %>
      </div>
    </div>  
    <div class="col">      
      <div class="field">
        <%= file_field :imagen_firma, :image %>
        &nbsp;
        <%# image_tag @imagen_firma.image.url(:med) if !@imagen_firma.nil? %>
        <%= mostrar_imagen(@imagen_firma).html_safe %>
      </div>
    </div>
 </div>

app/views/cfg_usuarios/_lista_usuarios.html.erb
<% if !@cfg_usuarios.nil? and @cfg_usuarios.size > 0 %>
  <table class="table table-bordered table-hover table-striped"><!--  table-responsive-->
    <thead>
      <tr>        
        <th scope="col">Login</th>
        <th scope="col">Perfil</th>
        <th scope="col">Identificación</th>
        <th scope="col">Tipo Usuario</th>
        <th scope="col">Nombres</th>  
        <th scope="col">Apellidos</th>
        <th scope="col">Empresa-Sede </th>
        <th scope="col">Estatus Cuenta</th>         
        <th scope="col" colspan="4">Operaciones</th>
      </tr>
    </thead>

    <tbody>
      <% @cfg_usuarios.each do |cfg_usuario| %>
        <tr>
          <td><%= cfg_usuario.login_usuario %></td>
          <td><%= cfg_usuario.nombre_perfil %></td>
          <td><%= cfg_usuario.descripcion_tipo_identificacion %> - <%= cfg_usuario.identificacion %></td>
          <td><%= cfg_usuario.nombre_tipo_usuario %></td>
          <td><%= cfg_usuario.nombres %></td>          
          <td><%= cfg_usuario.apellidos %></td>  
          <td>
             <%= cfg_usuario.razon_social %> 
             <%# if !cfg_usuario.nombre_sede.blank? %>
                 - <%= cfg_usuario.nombre_sede %> 
             <%# end %>
          </td>          
          <td><%= cfg_usuario.estado_cuenta_descripcion? %></td>
          <td align="center">           
            <%= link_to(cfg_usuario) do %>           
              <span class="oi oi-magnifying-glass" title="Consultar" aria-hidden="true"></span>
            <% end %> 
          </td>
          <td align="center">           
            <%= link_to(reiniciar_clave_cfg_usuario_path(cfg_usuario)) do %>
              <span class="oi oi-key" title="Cambiar contraseña" aria-hidden="true"></span>  
            <% end %>
          </td>
          <td align="center">           
            <%= link_to(edit_cfg_usuario_path(cfg_usuario)) do %>
              <span class="oi oi-pencil" title="Editar" aria-hidden="true"></span>  
            <% end %>
          </td>
          <td align="center">
            <%= link_to(estatus_usuario_path(cfg_usuario, devolver_valor_activo(cfg_usuario.estado_cuenta)), method: :post,data: { confirm: '¿Está seguro que desea activar/inactivar la cuenta del usuario?' }) do %>           
                 <%= mostrar_operacion_activar(cfg_usuario.estado_cuenta).html_safe  %>
            <% end %> 
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <div class="sin_registros"> No existen usuarios registrados </div> 
<% end %>  

app/views/cfg_usuarios/_modal_buscar_usuarios.html.erb
<div id="modal_buscar_usuarios" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Buscar usuarios</h5>
      </div>
      <%# form_for @cfg_usuario, remote: true do |f| %>
      <%= form_for :cfg_usuario, url: buscar_cfg_usuarios_path,  remote: true, 
          :html => {:method => "get", :id => "form" } do |f| %>
        <!-- modal-body -->
        <div class="modal-body">
            <!-- Búsqueda por login y nombres/apellidos-->
            <div class="row">
              <div class="col">
                <%= label_tag 'login', 'Login', class: "control-label" %>    
              </div>
              <div class="col">
                <%= label_tag 'identificacion', 'Identificación', class: "control-label" %>    
              </div>
            </div>
            <div class="row">
              <div class="col">
                <div class="form-group">    
                  <%= text_field_tag 'login', nil, class: "form-control", placeholder: "INGRESE EL LOGIN", maxlength: 15 %>
                </div>
              </div>
              <div class="col">  
                <div class="form-group">    
                  <%= text_field_tag 'identificacion', nil, class: "form-control", placeholder: "INGRESE LA IDENTIFICACION", maxlength: 50 %>
                </div>
              </div>
            </div>
            <!-- Búsqueda por nombre/ apellido  -->
            <div class="row">
              <div class="col">
                  <%= label_tag 'nombre_apellidos', 'Nombres o Apellidos', class: "control-label" %>    
              </div>
            </div>  
            <div class="row">
              <div class="col">
                  <div class="form-group">    
                  <%= text_field_tag 'nombres_apellidos', nil, class: "form-control", placeholder: "INGRESE EL NOMBRE O APELLIDO", maxlength: 15, style: "text-transform: uppercase" %>
                </div>
              </div>
            </div>   
            <!-- Búsqueda por perfil de usuario / tipo de usuario -->
            <div class="row">
              <div class="col">
                  <%= label_tag 'perfil_id', 'Perfil', class: "control-label" %>    
              </div>
              <div class="col">
                  <%= label_tag 'tipo_usuario_id', 'Tipo de Usuario', class: "control-label" %>    
              </div>
            </div>  
            <div class="row">
              <div class="col">  
                <div class="form-group"> 
                  <% perfiles = obtener_perfiles_usuarios_activos %>
                  <%= select_tag 'perfil_id', options_for_select(perfiles.collect{ |u| [u.nombre_perfil, u.id] }), {class: "form-control", :include_blank => true} %>
                </div>
              </div>
              <div class="col">  
                <div class="form-group">    
                  <% tipo_usuarios = obtener_tipo_usuarios %>
                  <%= select_tag 'tipo_usuario_id', options_for_select(tipo_usuarios.collect{ |u| [u.descripcion, u.id] }), {class: "form-control", :include_blank => true} %>
                </div>
              </div>
            </div>    
            <!-- Búsqueda por empresa / sede -->
            <div class="row">
              <div class="col">
                  <%= label_tag 'empresa_id', 'Empresa', class: "control-label" %>    
              </div>
              <div class="col">
                  <%= label_tag 'sede_id', 'Sede', class: "control-label" %>    
              </div>
            </div>  
            <div class="row">
              <div class="col">  
                <div class="form-group"> 
                  <% empresas = obtener_empresas_todas %>
                  <%= select_tag 'empresa_id', options_for_select(empresas.collect{ |u| [u.razon_social, u.id] }), {class: "form-control", :include_blank => true} %>
                </div>
              </div>
              
              <div class="col">  
                <div class="form-group">    
                  <div id="area_sedes">  
                  <%= render 'sedes', empresa_id: params[:empresa_id] %>
                  </div>
                </div>
              </div>

            </div> 
            <!-- Búsqueda por empresa / sede -->
            <div class="row">
              <div class="col">
                  <%= label_tag 'estado_cuenta', 'Estatus Cuenta', class: "control-label" %>    
              </div>
            </div>  
            <div class="row">
              <div class="col">
                <div class="form-group"> 
                  <% estados_cuenta = obtener_estatus_activo_inactivo%>
                  <%= select_tag 'estado_cuenta', options_for_select(estados_cuenta.collect{ |u| [u[0], u[1]] }), {class: "form-control", :include_blank => true} %>
                </div>    
              </div>
            </div> 


            <!-- --> 
        </div><!-- fin modal-body-->
        <!-- BOTONES -->
        <div class="modal-footer">          
          <%= f.submit " Buscar ", class: "btn btn-primary", id: "enviar" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button> 
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/cfg_usuarios/_paginacion.html.erb
<!-- PAGINACION-->
<center>
  <%= paginate @cfg_usuarios %>
  <%= page_entries_info @cfg_usuarios %>
</center>

app/views/cfg_usuarios/_sedes.html.erb
<% sedes = obtener_sedes_todas(empresa_id) %>
<%= select_tag 'sede_id', options_for_select(sedes.collect{ |u| [u.nombre_sede, u.id] }), {class: "form-control", :include_blank => true} %>

app/views/cfg_usuarios/actualizar_sedes_por_empresa.js.erb
$("#area_sedes").html("<%= j render(:partial => 'sedes.html.erb', :locals => {:empresa_id => params[:empresa_id] } ) %>");

app/views/cfg_usuarios/buscar.js.erb
$("#lista").html("<%= j render 'lista_usuarios' %>");
$("#paginacion").html("<%= j render 'paginacion' %>");
$("#modal_buscar_usuarios").modal("hide");

app/views/cfg_usuarios/index.html.erb
<SCRIPT>
  $(document).ready(function(){
      // Al cambiar el combo de empresa,
      // actualizar las sedes 
      $("#empresa_id").change(function() {    
        $.ajax({
          url: "/cfg_usuarios/actualizar_sedes_por_empresa",
          type: "POST",
          data: { "empresa_id": $(this).val() },
          success: function(resp){}
        });   
      });
  }); 
</SCRIPT>

<h2> Usuarios</h2>
<br/>
<div class="actions text-left">
    <%= link_to 'Usuario', new_user_registration_path %> <br/>
    <%= link_to "Buscar", "#modal_buscar_usuarios", "data-toggle" => "modal" %>
</div>
<!-- VENTANA MODAL CON LOS CRITERIOS DE BUSQUEDA-->
<%= render 'modal_buscar_usuarios' %>

<!-- LISTA DE LOS USUARIOS -->
<div id="lista">
   <%= render 'lista_usuarios' %>
</div>
<br/>
<div id="paginacion">
   <%= render 'paginacion' %>
</div>

app/views/cfg_usuarios/reiniciar_clave.html.erb
<h2>Reiniciar Clave de Usuario</h2><br/>

<%= a = []
    a << @user if !@user.nil?
    render 'general/errores', modelos: a %>

<%= render 'datos_usuario'%><br/>
<%# form_for(@user, :url => {:controller => "cfg_usuarios", :action => "guardar_reinicio_clave" } ) do |f| %>
<%# form_for(@user, url: guardar_reinicio_clave_cfg_usuario_path(@cfg_usuario) ) do |f| %>
<%# form_for(@cfg_usuario, url: guardar_reinicio_clave_path(@cfg_usuario) ) do |f| %>
<%= form_for :user, url: {action: "guardar_reinicio_clave"}, :method => :POST do |f| %>
  <h4>Datos de la Cuenta</h4>
  <hr/>
  <div class="row">
    <div class="col">     
      <%= f.label :password, 'Clave', class: "control-label required" %>  
    </div>
    <div class="col">     
      <%= f.label :password_confirmation, 'Confirmación Clave', class: "control-label required" %>  
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.password_field :password, {class: "form-control", autocomplete: "off", required: true, placeholder: "INGRESE LA CLAVE", maxlength: 20 } %>
    </div>
    <div class="col">
       <%= f.password_field :password_confirmation, {class: "form-control", autocomplete: "off", required: true, placeholder: "INGRESE LA CONFIRMACION DE LA CLAVE", maxlength: 20 } %>
    </div>  
  </div>

  <!-- BOTONES -->
  <br/><br/>
  <div class="actions text-center">
    <%= f.submit " Guardar ", class: "btn btn-primary" %>    
    <%= link_to 'Regresar', cfg_usuarios_path, class: "btn btn-secondary" %>
  </div>

<% end %>