config/routes.rb
Rails.application.routes.draw do

  resources :cfg_opciones_menus do
    collection do
      get 'buscar'
    end
    resources :cfg_operaciones_opciones_menu
  end
  resources :cfg_perfiles_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_operaciones'
      post 'guardar_operacion_opcion'
      post 'guardar_todas_operacion_opcion'
    end
    member do
      get 'asociar_opciones_menu'
      post 'guardar_asociar_opciones_menu'
    end
  end
  resources :cfg_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_sedes_por_empresa'
    end
    member do
      get 'reiniciar_clave'
      post 'guardar_reinicio_clave'
    end 
  end
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'my_devise/registrations'  }
  
  resources :cfg_pacientes
  resources :cfg_items_horarios
  resources :cfg_horarios do
    collection do
      post 'listar_horarios'  
      post 'editar_horarios'    
    end
  end
  resources :cfg_empresas do
    resources :cfg_sedes do
      resources :cfg_consultorios
    end    
  end

  resources :cit_turnos do
    collection do
      post 'buscar_usuario'
      post 'buscar_horarios'
      post 'buscar_agenda'
      post 'buscar_evento'      
      get 'search'
      post 'buscar'
      post 'buscar_prestador'
    end
    resources :cit_citas
  end

  resources :cfg_dias_no_laborales
  resources :citas do
    collection do
      post 'buscar_usuario'
      post 'buscar_agenda'
      post 'buscar_paciente'
      post 'cancelar_cita'
      get 'usuarios'
    end
  end
  root 'bienvenida#index'
  get 'bienvenida/index'
  resources :especialidades
  post '/cfg_empresas/:id/:activo', to: 'cfg_empresas#estatus_empresa', as: 'estatus_empresa'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:id/:activo', to: 'cfg_sedes#estatus_sede', as: 'estatus_sede'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:cfg_sede_id/cfg_consultorios/:id/:activo', to: 'cfg_consultorios#estatus_consultorio', as: 'estatus_consultorio'
  post '/cfg_pacientes/buscar_pacientes', to: 'cfg_pacientes#buscar_pacientes', as: 'buscar_pacientes'
  post '/cfg_pacientes/buscar_paciente', to: 'cfg_pacientes#buscar_paciente', as: 'buscar_paciente'
  # usuarios
  post '/cfg_usuarios/:id/:activo', to: 'cfg_usuarios#estatus_usuario', as: 'estatus_usuario'
  post '/cfg_perfiles_usuarios/:id/:activo', to: 'cfg_perfiles_usuarios#estatus_perfil', as: 'estatus_perfil'
  post '/cfg_opciones_menus/:id/:activo', to: 'cfg_opciones_menus#estatus_opcion', as: 'estatus_opcion'
  post '/cfg_opciones_menu/:cfg_opciones_menu_id/cfg_operaciones_opciones_menu/:id/:activo', to: 'cfg_operaciones_opciones_menu#estatus_operacion', as: 'estatus_operacion' 
  post '/cit_citas/buscar_paciente_cita', to: 'cit_citas#buscar_paciente_cita', as: 'buscar_paciente_cita'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Errores generados por id's o recursos no existentes, entre otros
  get 'errors/not_found'
  get 'errors/internal_server_error'  
  get '*path', to: 'application#routing_error'
  # Obligatoriamente va en el último lugar. Caso contrario, devuelve cualquier request, así no tenga error
  get '*unmatched_route', to: 'errors#not_found'
end

app/models/cfg_opciones_menu.rb
class CfgOpcionesMenu < ApplicationRecord
  has_many :cfg_operaciones_opciones_menu
  after_validation :validaciones_crear, on: [:create] 
  after_validation :validaciones_actualizar, on: [:update] 

  # Relaciones con otros modelos    
  has_many :cfg_opciones_menu_perfil_usuarios
  
  # Validaciones de campos obligatorios
  validates :id_opcion_padre, presence: {message: "Opción padre: debe seleccionar el valor"}
  validates :nombre_opcion, presence: {message: "Nombre de la opción: debe ingresar el valor"}
  #validates :style, presence: {message: "Estilo: debe ingresar el valor"}
  validates :url_opcion, presence: {message: "Url de la opción: debe ingresar el valor"}
  validates :orden, presence: {message: "Orden de la opción: debe ingresar el valor"}
  validates :activo, inclusion: { in: [true, false], message: "Debe seleccionar algún valor si / no" }

  # Llamado a método para cambiar contenido a mayúsculas
  before_validation :cambiar_mayusculas, on: [:create, :update] 

  #def esta_activo?
  #  self.activo == false ?'No':'Si'
  #end  

  def estatus?(valor)
      valor == true ?'SI':'NO'
  end

  def descripcion_opcion_padre
    descripcion = ""
    if self.id_opcion_padre == 0
      descripcion = "---"
    else  
      nivel1 = CfgOpcionesMenu.find(self.id_opcion_padre)
      if !nivel1.nil?
        nivel2 = CfgOpcionesMenu.find(nivel1.id_opcion_padre)
        if !nivel2.nil?
          if nivel2.nombre_opcion.blank?
            descripcion = nivel1.nombre_opcion.upcase
          else
            descripcion = nivel2.nombre_opcion.upcase + " - " + nivel1.nombre_opcion.upcase
          end
        else
          descripcion = nivel1.nombre_opcion.upcase
        end
      end
    end  
    return descripcion
  end

  def validaciones_crear
    # Verificar que el nombre no esté ya previamente registrado
    if !self.nombre_opcion.blank?
      nombre_opcion = self.nombre_opcion.strip  
      opciones = CfgOpcionesMenu.select("id").where("UPPER(nombre_opcion) = ?", nombre_opcion.upcase)
      self.errors.add("nombre_opcion", "Nombre de opción ya existe") if opciones.size > 0
    end
  end

  def validaciones_actualizar
    # Verificar que el nombre no esté ya previamente registrado
    if !self.nombre_opcion.blank?
      nombre_opcion = self.nombre_opcion.strip    
      opciones = CfgOpcionesMenu.select("id")
                 .where("UPPER(nombre_opcion) = ?", nombre_opcion.upcase)
                 .where("id <> ?", self.id)
      self.errors.add("nombre_opcion", "Nombre de opción ya existe") if opciones.size > 0
    end
  end

  protected
  	def cambiar_mayusculas
      self.nombre_opcion = nombre_opcion.upcase if !nombre_opcion.blank?      
  	end

end

app/controllers/cfg_opciones_menus_controller.rb
class CfgOpcionesMenusController < ApplicationController
  before_action :set_cfg_opciones_menu, only: [:show, :edit, :update, :destroy, :estatus_opcion]

  # GET /cfg_opciones_menu
  # GET /cfg_opciones_menu.json
  def index
    query_listar_opciones
  end

  # Buscar segun la ventana de criterios de busqueda
  # Y la paginacion, despues de haber filtrado por algun criterio 
  # de busqueda
  def buscar
    # Ejecuta el query
    query_listar_opciones
    # Si la accion es buscar por los criterios de busqueda, va al js
    # De lo contrario va al index    
    if !params[:commit].nil? and params[:commit].strip == "Buscar"
      render "buscar.js"
    else
      render :index
    end  
  end

  def query_listar_opciones
    # Variables para la condicion y valores del query
    condiciones = []
    argumentos = Hash.new 

    # Criterio de busqueda: nombre 
    unless params[:nombre].blank?
      condiciones << 'compara_ascii(UPPER(cfg_opciones_menu.nombre_opcion)) ILIKE compara_ascii(UPPER(:nombre))'
      argumentos[:nombre] = "%"+params[:nombre].strip+"%"
    end
    # Criterio de busqueda: nombre_padre
    unless params[:nombre_padre].blank?
      #compara_ascii(UPPER(cfg_opciones_menu.nombre_opcion)) ILIKE compara_ascii(UPPER(:nombre_padre))                    OR 
      condiciones << 'compara_ascii(UPPER(cfg_opciones_menu_2.nombre_opcion)) ILIKE compara_ascii(UPPER(:nombre_padre))
                     OR compara_ascii(UPPER(cfg_opciones_menu_3.nombre_opcion)) ILIKE compara_ascii(UPPER(:nombre_padre))'
      argumentos[:nombre_padre] = "%"+params[:nombre_padre].strip+"%"
    end
    # Criterio de busqueda: url
    unless params[:url].blank?
      condiciones << 'compara_ascii(UPPER(cfg_opciones_menu.url_opcion)) ILIKE compara_ascii(UPPER(:url))'
      argumentos[:url] = "%"+params[:url].strip+"%"
    end
    # Criterio de búsqueda: activo
    unless params[:activo].blank?
      condiciones << 'cfg_opciones_menu.activo = :activo'
      argumentos[:activo] = params[:activo]
    end

    # Query original
    #@cfg_opciones_menu = CfgOpcionesMenu.select("id, id_opcion_padre, orden, nombre_opcion, url_opcion, activo")   
    #.order('nombre_opcion').page(params[:page])
    #.where(condiciones.join(" AND "),argumentos)

    @cfg_opciones_menu = CfgOpcionesMenu.select("cfg_opciones_menu.id, cfg_opciones_menu.id_opcion_padre, cfg_opciones_menu.orden, 
                         cfg_opciones_menu.nombre_opcion, cfg_opciones_menu.url_opcion, cfg_opciones_menu.activo,
                         cfg_opciones_menu_2.nombre_opcion AS nombre_opcion_sup1, cfg_opciones_menu_3.nombre_opcion AS nombre_opcion_sup2   ")   
    .joins("JOIN cfg_opciones_menu cfg_opciones_menu_2 ON cfg_opciones_menu.id_opcion_padre = cfg_opciones_menu_2.id
            JOIN cfg_opciones_menu cfg_opciones_menu_3 ON cfg_opciones_menu_2.id_opcion_padre = cfg_opciones_menu_3.id ")
    .order('cfg_opciones_menu.nombre_opcion').page(params[:page])
    .where(condiciones.join(" AND "),argumentos)


  end

  # GET /cfg_opciones_menu/1
  # GET /cfg_opciones_menu/1.json
  def show
  end

  # GET /cfg_opciones_menu/new
  def new
    @cfg_opciones_menu = CfgOpcionesMenu.new
  end

  # GET /cfg_opciones_menu/1/edit
  def edit
  end

  # POST /cfg_opciones_menu
  # POST /cfg_opciones_menu.json
  def create
    begin
      @cfg_opciones_menu = CfgOpcionesMenu.new(cfg_opciones_menu_params)
      @cfg_opciones_menu.save!
      # Redireccionar al consultar 
      redirect_to @cfg_opciones_menu, notice: 'La opción de menú fue creada satisfactoriamente'               
    rescue ActiveRecord::RecordInvalid =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar la opción de menú"
      render :new
    rescue ActiveRecord::RecordNotUnique =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar la opción de menú - id no es único"
      render :new  
    rescue => exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar la opción de menú"
      render :new
    end
  end

  # PATCH/PUT /cfg_opciones_menu/1
  # PATCH/PUT /cfg_opciones_menu/1.json
  def update
    begin
      # Actualizar información
      @cfg_opciones_menu.update_attributes!(cfg_opciones_menu_params)
      puts "si actualizo..."
      # Redireccionar al consultar 
      redirect_to @cfg_opciones_menu, notice: 'La opción de menú fue actualizada satisfactoriamente'         
    rescue ActiveRecord::RecordInvalid =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar la opción de menú - registro inválido"
      render :edit
    rescue ActiveRecord::RecordNotUnique =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar la opción de menú - id no es único"
      render :edit    
    rescue => exception
      imprimir_mensajes_excepcion(exception)
      render :edit      
    end
  end

  # METODO QUE ACTUALIZA EL ESTATUS ACTIVO DE LA OPCION
  def estatus_opcion
    if @cfg_opciones_menu.update(activo: !devolver_valor_activo(params[:activo]))
      flash[:notice] = "Estatus de la opción de menú fue actualizado satisfactoriamente"      
    else
      flash[:alert] = "Estatus de la opción de menú no pudo ser actualizado"  
      # Mostrar junto al mensaje de alert, los errores del modelo
      @cfg_opciones_menu.errors.each do |campo,msg| 
        flash[:alert] = flash[:alert]  + "<BR>"
        flash[:alert] = flash[:alert]  + msg 
      end
    end
    redirect_to cfg_opciones_menus_url  
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cfg_opciones_menu
      @cfg_opciones_menu = CfgOpcionesMenu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cfg_opciones_menu_params
      params.require(:cfg_opciones_menu).permit(:nombre_opcion, :id_opcion_padre, :url_opcion, :orden, :activo, :observaciones)
    end
end

app/helpers/cfg_opciones_menus_helper.rb
module CfgOpcionesMenusHelper

  def obtener_opciones_padres_activas
  	CfgOpcionesMenu.select("cfg_opciones_menu.id, cfg_opciones_menu.activo,
  		            UPPER(cfg_opciones_menu_padre.nombre_opcion) || ' - ' ||
                    UPPER(cfg_opciones_menu.nombre_opcion) as nombre_opcion")
  	  .joins("LEFT JOIN cfg_opciones_menu cfg_opciones_menu_padre  
  	  	     ON cfg_opciones_menu.id_opcion_padre = cfg_opciones_menu_padre.id")
      .where("cfg_opciones_menu.activo IS TRUE").
      order("cfg_opciones_menu_padre.nombre_opcion ASC, cfg_opciones_menu.nombre_opcion ASC")
  end
end

app/views/cfg_opciones_menus/_form.html.erb
<%= form_for(@cfg_opciones_menu, url: cfg_opciones_menus_path(@cfg_opciones_menu)) do |form| %>
  <%= a = []
    a << @cfg_opciones_menu
    render 'general/errores', modelos: a %>

  <div class="row">
    <div class="col"> 
      <%= form.label :nombre_opcion, 'Nombre', class: "control-label required" %>  
    </div>
    <div class="col"> 
      <%= form.label :id_opcion_padre, 'Opción padre', class: "control-label required" %>  
    </div>
  </div>  
  <div class="row">
    <div class="col">
      <div class="form-group">                        
        <%= form.text_field :nombre_opcion, {id: :cfg_opciones_menu_nombre_opcion, class: "form-control", style: "text-transform: uppercase",  required: true, placeholder: "Ingrese el nombre de la opción", maxlength: 40} %>
      </div>
    </div>
    <div class="col">
       <div class="form-group">   
          <%= form.collection_select(:id_opcion_padre, obtener_opciones_padres_activas, :id, :nombre_opcion, {:include_blank => 'SELECCIONE LA OPCION PADRE'}, {id: "cfg_opciones_menu_id_opcion_padre", class: "form-control", required: true} )%>
       </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col"> 
      <%= form.label :url_opcion, 'Url', class: "control-label required" %>  
    </div>
    <div class="col"> 
      <%= form.label :orden, 'Orden', class: "control-label required" %>  
    </div>
  </div> 
  <div class="row">
    <div class="col">
      <div class="form-group">  
        <%= form.text_field :url_opcion, {id: :cfg_opciones_menu_url_opcion, class: "form-control",  required: true, placeholder: "INGRESE EL URL DE LA OPCION", maxlength: 100} %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">  
        <%= form.number_field :orden, {min: 1, max: 50, step: 1, id: :cfg_opciones_menu_orden,
          class: "form-control",  required: true, placeholder: "INGRESE EL ORDEN"} %>
      </div>
    </div>
  </div>    
  
  <div class="row">
    <div class="col">     
      <%= form.label :activo, '¿Activo?', class: "control-label required" %>        
    </div>
    <div class="col">     
      <%= form.label :observaciones, 'Observaciones', class: "control-label" %>        
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="form-group">  
        <%= select(:cfg_opciones_menu, :activo, obtener_estatus_si_no, { prompt: "SELECCIONE EL ESTATUS ACTIVO"  }, {id: "cfg_opciones_menu_activo", class: "form-control", required: true }) %>
      </div>
    </div>
    <div class="col">
      <div class="form-group"> 
         <%= form.text_area :observaciones, {id: :cfg_opciones_menu_observaciones, class: "form-control", style: "text-transform: uppercase", placeholder: "Ingrese las observaciones", maxlength: 400} %>
      </div>
    </div>  
  </div>  

  <!-- BOTONES -->
  <br/>
  <hr>
  <div class="actions text-center">
    <%= form.submit " Guardar ", class: "btn btn-primary" %>    
    <%= link_to 'Regresar', cfg_opciones_menus_path, class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/cfg_opciones_menus/_lista_opciones.html.erb
<% if !@cfg_opciones_menu.nil? and @cfg_opciones_menu.size > 0 %>
<table class="table table-bordered table-hover table-striped"><!--  table-responsive-->
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Opción Padre</th>
      <th>Url</th>
      <th>Orden</th>
      <th>¿Activo?</th>
      <th colspan="4">Operaciones</th>
    </tr>
  </thead>

  <tbody>
    <% @cfg_opciones_menu.each do |cfg_opciones_menu| %>
      <tr>
        <td><%= cfg_opciones_menu.nombre_opcion.upcase %></td>
        <td>
          <%# cfg_opciones_menu.id_opcion_padre %>
          <%= cfg_opciones_menu.descripcion_opcion_padre %>    
        </td>
        <td><%= cfg_opciones_menu.url_opcion %></td>
        <td><%= cfg_opciones_menu.orden %></td>
        <td><%= cfg_opciones_menu.estatus?(cfg_opciones_menu.activo) %></td>
        
        <td align="center">           
          <%= link_to(cfg_opciones_menu) do %>           
            <span class="oi oi-magnifying-glass" title="Consultar" aria-hidden="true"></span>
          <% end %> 
        </td>
        <td align="center">           
          <%= link_to(edit_cfg_opciones_menu_path(cfg_opciones_menu)) do %>
            <span class="oi oi-pencil" title="Editar" aria-hidden="true"></span>  
          <% end %>
        </td>
        <td align="center">
            <%= link_to(estatus_opcion_path(cfg_opciones_menu, devolver_valor_activo(cfg_opciones_menu.activo)), method: :post,data: { confirm: '¿Está seguro que desea activar/inactivar la opción del menú?' }) do %>           
                 <%= mostrar_operacion_activar(cfg_opciones_menu.activo).html_safe  %>
            <% end %> 
        </td>
        <td align="center">
          <%= link_to(cfg_opciones_menu_cfg_operaciones_opciones_menu_index_path(cfg_opciones_menu)) do %>          
          <span class="oi oi-list" title="Asociar Operaciones" aria-hidden="true"></span>
        <% end %>
        </td>  
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
  <div class="sin_registros"> No existen opciones registradas </div> 
<% end %>  

app/views/cfg_opciones_menus/_modal_buscar_opciones.html.erb
<div id="modal_buscar_opciones" class="modal fade">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Buscar opciones de menú</h5>
      </div>
      <%= form_for :cfg_opciones_menu, url: buscar_cfg_opciones_menus_path,  
          remote: true, :html => {:method => "get", :id => "form" } do |f| %>
        <!-- modal-body -->
        <div class="modal-body">
            <!-- Búsqueda por nombre / nombre_padre -->
            <div class="row">
              <div class="col">
                  <%= label_tag 'nombre', 'Nombre de Opción', class: "control-label" %>    
              </div>
              <div class="col">
                  <%= label_tag 'nombre_padre', 'Nombre de Opción Padre', class: "control-label" %>    
              </div>
            </div>  
            <div class="row">
              <div class="col">
                <div class="form-group">    
                  <%= text_field_tag 'nombre', nil, class: "form-control", placeholder: "INGRESE EL NOMBRE ", maxlength: 40, style: "text-transform: uppercase" %>
                </div>
              </div>
              <div class="col">
                <div class="form-group">    
                  <%= text_field_tag 'nombre_padre', nil, class: "form-control", placeholder: "INGRESE EL NOMBRE DE LA OPCION PADRE", maxlength: 40, style: "text-transform: uppercase" %>
                </div>
              </div>
            </div>   
            <!-- Búsqueda por url / activo  -->
            <div class="row">
              <div class="col">
                  <%= label_tag 'url', 'Url', class: "control-label" %>    
              </div>
              <div class="col">
                  <%= label_tag 'activo', '¿Activo?', class: "control-label" %>    
              </div>
            </div>  
            <div class="row">
              <div class="col">
                <div class="form-group"> 
                  <%= text_field_tag 'url', nil, class: "form-control", placeholder: "INGRESE EL URL", maxlength: 40, style: "text-transform: uppercase" %>
                </div>    
              </div>
              <div class="col">
                <div class="form-group"> 
                  <% estatus = obtener_estatus_si_no %>
                  <%= select_tag 'activo', options_for_select(estatus.collect{ |u| [u[0], u[1]] }), {class: "form-control", :include_blank => 'SELECCIONE EL ESTATUS ACTIVO'} %>
                  <%# select_tag "activo", options_for_select(estatus.collect{ |u| [u[0], u[1]] }), include_blank: true %>
                </div>   
              </div>
            </div> 


            <!-- --> 
        </div><!-- fin modal-body-->
        <!-- BOTONES -->
        <div class="modal-footer">          
          <%= f.submit "Buscar", class: "btn btn-primary", id: "enviar" %>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button> 
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/cfg_opciones_menus/edit.html.erb
<h2>Editar Opción de Menú</h2>
<br/>
<%# render 'form', cfg_opciones_menus: @cfg_opciones_menu %>
<%= form_for(@cfg_opciones_menu, url: cfg_opciones_menu_path(@cfg_opciones_menu), method: :put) do |form| %>
  <%= a = []
    a << @cfg_opciones_menu
    render 'general/errores', modelos: a %>

  <div class="row">
    <div class="col"> 
      <%= form.label :nombre_opcion, 'Nombre', class: "control-label required" %>  
    </div>
    <div class="col"> 
      <%= form.label :id_opcion_padre, 'Opción padre', class: "control-label required" %>  
    </div>
  </div>  
  <div class="row">
    <div class="col">
      <div class="form-group">                        
        <%= form.text_field :nombre_opcion, {id: :cfg_opciones_menu_nombre_opcion, class: "form-control", style: "text-transform: uppercase",  required: true, placeholder: "Ingrese el nombre de la opción", maxlength: 40} %>
      </div>
    </div>
    <div class="col">
       <div class="form-group">   
          <%= form.collection_select(:id_opcion_padre, obtener_opciones_padres_activas, :id, :nombre_opcion, {:include_blank => 'SELECCIONE LA OPCION PADRE'}, {id: "cfg_opciones_menu_id_opcion_padre", class: "form-control", required: true} )%>
       </div>
    </div>
  </div>
  
  <div class="row">
    <div class="col"> 
      <%= form.label :url_opcion, 'Url', class: "control-label required" %>  
    </div>
    <div class="col"> 
      <%= form.label :orden, 'Orden', class: "control-label required" %>  
    </div>
  </div> 
  <div class="row">
    <div class="col">
      <div class="form-group">  
        <%= form.text_field :url_opcion, {id: :cfg_opciones_menu_url_opcion, class: "form-control",  required: true, placeholder: "INGRESE EL URL DE LA OPCION", maxlength: 100} %>
      </div>
    </div>
    <div class="col">
      <div class="form-group">  
        <%= form.number_field :orden, {id: :cfg_opciones_menu_orden,
          class: "form-control",  required: true, placeholder: "INGRESE EL ORDEN"} %>
      </div>
    </div>
  </div>    
  
  <div class="row">
    <div class="col">     
      <%= form.label :activo, '¿Activo?', class: "control-label required" %>        
    </div>
    <div class="col">     
      <%= form.label :observaciones, 'Observaciones', class: "control-label" %>        
    </div>
  </div>
  <div class="row">
    <div class="col">
      <div class="form-group">  
        <%= select(:cfg_opciones_menu, :activo, obtener_estatus_si_no, { prompt: "SELECCIONE EL ESTATUS ACTIVO"  }, {id: "cfg_opciones_menu_activo", class: "form-control", required: true }) %>
      </div>
    </div>
    <div class="col">
      <div class="form-group"> 
         <%= form.text_area :observaciones, {id: :cfg_opciones_menu_observaciones, class: "form-control", style: "text-transform: uppercase", placeholder: "Ingrese las observaciones", maxlength: 400} %>
      </div>
    </div>  
  </div>  

  <!-- BOTONES -->
  <br/>
  <hr>
  <div class="actions text-center">
    <%= form.submit " Guardar ", class: "btn btn-primary" %>    
    <%= link_to 'Regresar', cfg_opciones_menus_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cfg_opciones_menus/show.html.erb
<h2>Consultar Opción de Menú</h2>
<br/>
<div class="row">
  <div class="col titulos-campos">     
    Nombre
  </div>
  <div class="col titulos-campos">     
    Opción Padre
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_opciones_menu.nombre_opcion.upcase %>&nbsp;
  </div>  
  <div class="col"> 
    <%# @cfg_opciones_menu.id_opcion_padre %>
    <%= @cfg_opciones_menu.descripcion_opcion_padre %>
    &nbsp;
  </div>  
</div>  

<div class="row">
  <div class="col titulos-campos">     
    Url
  </div>
  <div class="col titulos-campos">     
    Orden
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_opciones_menu.url_opcion %>&nbsp;
  </div>  
  <div class="col"> 
    <%= @cfg_opciones_menu.orden %>&nbsp;
  </div>  
</div> 

<div class="row">
  <div class="col titulos-campos">     
    ¿Activo?
  </div>
  <div class="col titulos-campos">     
    Observaciones
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_opciones_menu.estatus?(@cfg_opciones_menu.activo) %>&nbsp;
  </div>  
  <div class="col"> 
    <%= @cfg_opciones_menu.observaciones.upcase if !@cfg_opciones_menu.observaciones.blank? %>&nbsp;
  </div>  
</div> 

<br>
<hr/>
<div class="actions text-center">
    <%= link_to 'Editar', edit_cfg_opciones_menu_path(@cfg_opciones_menu), class: "btn btn-primary" %>  
    <%= link_to 'Regresar', cfg_opciones_menus_path, class: "btn btn-primary" %>
</div>