config/routes.rb
Rails.application.routes.draw do

  resources :cfg_opciones_menus do
    collection do
      get 'buscar'
    end
    resources :cfg_operaciones_opciones_menu
  end
  resources :cfg_perfiles_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_operaciones'
      post 'guardar_operacion_opcion'
      post 'guardar_todas_operacion_opcion'
    end
    member do
      get 'asociar_opciones_menu'
      post 'guardar_asociar_opciones_menu'
    end
  end
  resources :cfg_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_sedes_por_empresa'
    end
    member do
      get 'reiniciar_clave'
      post 'guardar_reinicio_clave'
    end 
  end
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'my_devise/registrations'  }
  
  resources :cfg_pacientes
  resources :cfg_items_horarios
  resources :cfg_horarios do
    collection do
      post 'listar_horarios'  
      post 'editar_horarios'    
    end
  end
  resources :cfg_empresas do
    resources :cfg_sedes do
      resources :cfg_consultorios
    end    
  end

  resources :cit_turnos do
    collection do
      post 'buscar_usuario'
      post 'buscar_horarios'
      post 'buscar_agenda'
      post 'buscar_evento'      
      get 'search'
      post 'buscar'
      post 'buscar_prestador'
    end
    resources :cit_citas
  end

  resources :cfg_dias_no_laborales
  resources :citas do
    collection do
      post 'buscar_usuario'
      post 'buscar_agenda'
      post 'buscar_paciente'
      post 'cancelar_cita'
      get 'usuarios'
    end
  end
  root 'bienvenida#index'
  get 'bienvenida/index'
  resources :especialidades
  post '/cfg_empresas/:id/:activo', to: 'cfg_empresas#estatus_empresa', as: 'estatus_empresa'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:id/:activo', to: 'cfg_sedes#estatus_sede', as: 'estatus_sede'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:cfg_sede_id/cfg_consultorios/:id/:activo', to: 'cfg_consultorios#estatus_consultorio', as: 'estatus_consultorio'
  post '/cfg_pacientes/buscar_pacientes', to: 'cfg_pacientes#buscar_pacientes', as: 'buscar_pacientes'
  post '/cfg_pacientes/buscar_paciente', to: 'cfg_pacientes#buscar_paciente', as: 'buscar_paciente'
  # usuarios
  post '/cfg_usuarios/:id/:activo', to: 'cfg_usuarios#estatus_usuario', as: 'estatus_usuario'
  post '/cfg_perfiles_usuarios/:id/:activo', to: 'cfg_perfiles_usuarios#estatus_perfil', as: 'estatus_perfil'
  post '/cfg_opciones_menus/:id/:activo', to: 'cfg_opciones_menus#estatus_opcion', as: 'estatus_opcion'
  post '/cfg_opciones_menu/:cfg_opciones_menu_id/cfg_operaciones_opciones_menu/:id/:activo', to: 'cfg_operaciones_opciones_menu#estatus_operacion', as: 'estatus_operacion' 
  post '/cit_citas/buscar_paciente_cita', to: 'cit_citas#buscar_paciente_cita', as: 'buscar_paciente_cita'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Errores generados por id's o recursos no existentes, entre otros
  get 'errors/not_found'
  get 'errors/internal_server_error'  
  get '*path', to: 'application#routing_error'
  # Obligatoriamente va en el último lugar. Caso contrario, devuelve cualquier request, así no tenga error
  get '*unmatched_route', to: 'errors#not_found'
end

app/models/cfg_sede.rb
class CfgSede < ApplicationRecord
  # Llamado a método para cambiar contenido a mayúsculas
  before_validation :cambiar_mayusculas, on: [:create, :update] 
  # Relaciones con otros modelos  
  has_many :cfg_consultorios
  belongs_to :cfg_empresa
  belongs_to :cfg_municipio, optional: true

  # Validaciones 
  validates :codigo_sede, presence:  {message: "Código sede: debe ingresar el valor"}
  validates :nombre_sede, presence:  {message: "Nombre sede: debe ingresar el valor"}
  validates :cfg_municipio_id, presence: {message: "Departamento-Municipio: debe seleccionar algún valor"}

  def esta_activo?
    self.activo == false ?'No':'Si'
  end 

  protected
    def cambiar_mayusculas
      self.codigo_sede = codigo_sede.upcase if !codigo_sede.blank?      
      self.nombre_sede = nombre_sede.upcase if !nombre_sede.blank?
      self.encargado   = encargado.upcase   if !encargado.blank?
      self.direccion   = direccion.upcase   if !direccion.blank?
    end

end

app/controllers/cfg_sedes_controller.rb
class CfgSedesController < ApplicationController
  before_action :set_cfg_sedes
  before_action :set_cfg_sede, only: [:show, :edit, :update, :destroy, :estatus_sede]

  # GET cfg_empresas/1/cfg_sedes
  def index
    #@cfg_sedes = @cfg_empresa.cfg_sedes
    #@cfg_sedes = CfgSede.select("cfg_sedes.id, cfg_sedes.codigo_sede, cfg_sedes.nombre_sede, cfg_sedes.activo, cfg_sedes.cfg_empresa_id, cfg_sedes.cfg_municipio_id, cfg_departamentos.nombre || ' - ' || cfg_municipios.nombre AS descripcion_departamento_municipio").joins(:cfg_municipio => :cfg_departamento).where(activo: true, cfg_empresa_id: @cfg_empresa.id).order('nombre_sede')
  end

  # GET cfg_empresas/1/cfg_sedes/1
  def show
  end

  # GET cfg_empresas/1/cfg_sedes/new
  def new
    @cfg_sede = @cfg_empresa.cfg_sedes.build
  end

  # GET cfg_empresas/1/cfg_sedes/1/edit
  def edit
  end

  # POST cfg_empresas/1/cfg_sedes
  def create
    @cfg_sede = @cfg_empresa.cfg_sedes.build(cfg_sede_params)
    
    if @cfg_sede.save
      redirect_to([@cfg_sede.cfg_empresa, @cfg_sede], notice: 'Datos de la sede creados satisfactoriamente.')
    else
      render action: 'new'
    end
  end

  # PUT cfg_empresas/1/cfg_sedes/1
  def update
    if @cfg_sede.update_attributes(cfg_sede_params)
      redirect_to([@cfg_sede.cfg_empresa, @cfg_sede], notice: 'Datos de la sede actualizados satisfactoriamente.')
    else
      render action: 'edit'
    end
  end

  # DELETE cfg_empresas/1/cfg_sedes/1
  def destroy
    @cfg_sede.update(activo: false)
    respond_to do |format|
      format.html { redirect_to cfg_empresa_cfg_sedes_url(@cfg_empresa), notice: 'Sede inactiva.' }
      format.json { head :no_content }
    end         
  end

  def estatus_sede
    @cfg_sede.update(activo: !devolver_valor_activo(params[:activo]))
    respond_to do |format|
      format.html { redirect_to cfg_empresa_cfg_sedes_url(@cfg_empresa), notice: 'Estatus de la Sede actualizado.' }
      format.json { head :no_content }
    end    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cfg_sedes
      #@cfg_empresa = CfgEmpresa.where(id: params[:cfg_empresa_id], activo: true).first      
      @cfg_empresa = CfgEmpresa.find(params[:cfg_empresa_id])
    end

    def set_cfg_sede
      #@cfg_sede = @cfg_empresa.cfg_sedes.where(id: params[:id], activo: true).first
      #@cfg_sede = @cfg_empresa.cfg_sedes.where(id: params[:id]).first
      @cfg_sede = @cfg_empresa.cfg_sedes.find(params[:id])
    end
    
    #def set_cfg_empresa
    #  @cfg_empresa = CfgEmpresa.find(params[:cfg_empresa_id])
    #end

    # Only allow a trusted parameter "white list" through.
    def cfg_sede_params
      params.require(:cfg_sede).permit(:codigo_sede, :nombre_sede, :departamento, :municipio, :encargado, :direccion, :telefono1, :telefono2, :cfg_empresa_id, :cfg_municipio_id)
    end
end

app/helpers/cfg_sedes_helper.rb
module CfgSedesHelper
	def lista_todas_sedes_por_empresa(cfg_empresa)
		cfg_sedes = CfgSede.select("cfg_sedes.id, cfg_sedes.codigo_sede, cfg_sedes.nombre_sede, cfg_sedes.activo, cfg_sedes.cfg_empresa_id, cfg_sedes.cfg_municipio_id, cfg_departamentos.nombre || ' - ' || cfg_municipios.nombre AS descripcion_departamento_municipio")
		.joins(:cfg_municipio => :cfg_departamento)
		.where(cfg_empresa_id: cfg_empresa.id)
		.order('nombre_sede')
	end	

    def devolver_valor_activo(param)
      param == true ? 'true':'false'
    end

end

app/views/cfg_sedes/_datos_empresa.html.erb
<h2>Empresa</h2>
<div class="row">
  <div class="col titulos-campos">     
    Código empresa        
  </div>
  <div class="col titulos-campos">     
    Razón social
  </div>
  <div class="col titulos-campos">     
    Departamento-Municipio       
  </div>
</div>  
<div class="row">
  <div class="col"> 
    <%= cfg_empresa.codigo_empresa %>&nbsp;
  </div>
  <div class="col"> 
    <%= cfg_empresa.razon_social %>&nbsp;
  </div>  
  <div class="col">  
    <%= obtener_departamento_municipio(cfg_empresa.cfg_municipio_id) %>&nbsp;
  </div>
</div>   

app/views/cfg_sedes/_form.html.erb
<%= form_for([@cfg_empresa, @cfg_sede]) do |form| %>

<%= render 'general/errores', modelos: [@cfg_sede] %>

<div class="row">
  <div class="col"> 
    <%= form.label :codigo_sede, 'Código', class: "control-label required" %>  
  </div>
  <div class="col"> 
    <%= form.label :nombre_sede, 'Nombre', class: "control-label required" %>  
  </div>
  <div class="col"> 
    <%= form.label :cfg_municipio_id, 'Departamento-Municipio', class: "control-label required" %>   
  </div>
</div> 
<div class="row">
  <div class="col">
    <div class="form-group">      
      <%= form.text_field :codigo_sede, {class: "form-control", style: "text-transform: uppercase",  required: true, placeholder: "Ingrese el código", maxlength: 10} %>
    </div>
  </div>
  <div class="col">
    <div class="form-group">      
      <%= form.text_field :nombre_sede, {class: "form-control", style: "text-transform: uppercase", required: true, placeholder: "Ingrese el nombre", maxlength: 200} %>
    </div>
  </div>
  <div class="col">
    <div class="form-group">    
      <%= form.grouped_collection_select :cfg_municipio_id, CfgDepartamento.order(:nombre), :cfg_municipios, :nombre, :id, :nombre, {include_blank: true, prompt: "SELECCIONE EL DEPARTAMENTO-MUNICIPIO"}, {class: "form-control", required: true} %>
    </div>    
  </div>
</div>

<div class="row">  
  <div class="col">
   <%= form.label :direccion, 'Dirección', class: "control-label" %>   
  </div>  
</div>
<div class="row">
  <div class="col">
    <div class="form-group">    
       <%= form.text_field :direccion, {class: "form-control", style: "text-transform: uppercase", placeholder: "Ingrese la dirección", maxlength: 200} %>
    </div>
  </div>
</div>  


<div class="row">
  <div class="col">     
    <%= form.label :encargado, 'Encargado', class: "control-label" %>   
  </div>
  <div class="col">     
    <%= form.label :telefono1, 'Teléfono 1 ', class: "control-label" %>   
  </div>
  <div class="col"> 
    <%= form.label :telefono2, 'Teléfono 2 ', class: "control-label" %>   
  </div>  
</div>
<div class="row">
  <div class="col">
    <div class="form-group">    
      <%= form.text_field :encargado, {class: "form-control", style: "text-transform: uppercase", placeholder: "Ingrese el nombre del encargado", maxlength: 200} %>
    </div>
  </div>
  <div class="col">
    <div class="form-group">    
      <%= form.text_field :telefono1, {class: "form-control", placeholder: "INGRESE EL TELÉFONO", :data => {:mask=> '999-999-9999'}} %>
    </div>
  </div>  
  <div class="col">
    <div class="field">
      <%= form.text_field :telefono2, {class: "form-control", placeholder: "INGRESE EL TELÉFONO", :data => {:mask=> '999-999-9999'}} %>
    </div>
  </div>
</div>

<br><hr>
  <div class="actions text-center">
    <%= form.submit " Guardar ", class: "btn btn-primary" %>    
    <%# link_to 'Regresar', cfg_empresa_cfg_sedes_path, class: "btn btn-primary" %>
    <a class="btn btn-secondary" href="<%=params[:regresar]%>">Regresar</a>
  </div>
<% end %>

app/views/cfg_sedes/_lista_sedes.html.erb
<!-- LISTA DE LAS SEDES -->
<% cfg_sedes = lista_todas_sedes_por_empresa(@cfg_empresa) %>
<% if !cfg_sedes.nil? and cfg_sedes.size > 0 %>
    <table class="table table-bordered table-hover table-striped"><!--  table-responsive-->
      <thead>
          <tr>
            <th scope="col">Código</th>
            <th scope="col">Nombre</th>
            <th scope="col">Departamento-Municipio</th>
            <th scope="col">¿Activo?</th>  
            <th scope="col" colspan="3">Operaciones</th>
            <th scope="col">Consultorios</th>
          </tr>
      </thead>
    <% cfg_sedes.each do |cfg_sede| %>
      <tr>
        <td><%= cfg_sede.codigo_sede %></td>
        <td><%= cfg_sede.nombre_sede %></td>
        <td>
          <%# obtener_departamento_municipio(cfg_sede.cfg_municipio_id) %>
          <%= cfg_sede.descripcion_departamento_municipio %>         
        </td>
        <td><%= cfg_sede.esta_activo?%></td>
        
        <td align="center">           
          <%= link_to([cfg_sede.cfg_empresa, cfg_sede]) do %>           
            <span class="oi oi-magnifying-glass" title="Consultar" aria-hidden="true"></span>
          <% end %> 
        </td>
        <td align="center">           
          <%= link_to(edit_cfg_empresa_cfg_sede_path(cfg_sede.cfg_empresa, cfg_sede)) do %>
              <span class="oi oi-pencil" title="Editar" aria-hidden="true"></span>  
          <% end %>
        </td>
        <td align="center">
          <%= link_to(estatus_sede_path(cfg_sede.cfg_empresa, cfg_sede, devolver_valor_activo(cfg_sede.activo)), method: :post,data: { confirm: '¿Está seguro que desea activar/inactivar la sede?' }) do %>           
              <%= mostrar_operacion_activar(cfg_sede.activo).html_safe  %>
          <% end %> 
        </td>         
        <td>
          <%#link_to 'Crear', new_cfg_empresa_cfg_sede_cfg_consultorio_path(@cfg_empresa,cfg_sede) %>
          <a href="/cfg_empresas/<%=cfg_empresa.id%>/cfg_sedes/<%=cfg_sede.id%>/cfg_consultorios/new?regresar=<%=request.fullpath%>">Consultorio</a> <br/>
          <%= link_to 'Listar', cfg_empresa_cfg_sede_cfg_consultorios_path(@cfg_empresa,cfg_sede) %>    
        </td>
      </tr>
    <% end %>
    </table>
<% else %>
  <div class="sin_registros"> No existen sedes para la empresa seleccionada </div>  
<% end %>

app/views/cfg_sedes/edit.html.erb
<!-- INFORMACION DE LA EMPRESA SELECCIONADA -->
<%= render 'datos_empresa', cfg_empresa: @cfg_empresa %>
<br>
<h2>Editar Sede</h2>
<br/>
<%= render 'form' %>

app/views/cfg_sedes/index.html.erb
<!-- INFORMACION DE LA EMPRESA SELECCIONADA -->
<%= render 'datos_empresa', cfg_empresa: @cfg_empresa %>
<br/>
<h2>Sedes</h2>
<div class="actions text-left">
    <%# link_to 'Crear Sede', new_cfg_empresa_cfg_sede_path(params[:cfg_empresa_id]) %>
    <a href="/cfg_empresas/<%=@cfg_empresa.id%>/cfg_sedes/new?regresar=<%=request.path%>">Sede</a>
</div>

<!-- LISTA DE LAS SEDES -->
<%= render 'lista_sedes', cfg_empresa: @cfg_empresa %>
<br/>
<hr/>
<div class="actions text-center">    
    <%= link_to 'Regresar', cfg_empresas_path, class: "btn btn-primary" %>
</div>

app/views/cfg_sedes/new.html.erb
<!-- INFORMACION DE LA EMPRESA SELECCIONADA -->
<%= render 'datos_empresa', cfg_empresa: @cfg_empresa %>
<br>
<h2>Sede</h2>
<br/>
<%= render 'form' %>

app/views/cfg_sedes/show.html.erb
<!-- INFORMACION DE LA EMPRESA SELECCIONADA -->
<%= render 'datos_empresa', cfg_empresa: @cfg_empresa %>
<br>
<h2>Consultar Sede</h2>
<br>
<div class="row">
  <div class="col titulos-campos">
    Codigo sede    
  </div>
  <div class="col titulos-campos">
    Nombre sede    
  </div>
  <div class="col titulos-campos">
    Departamento    
  </div>
</div>
<div class="row">
  <div class="col">
    <%= @cfg_sede.codigo_sede %>
  </div>
  <div class="col">
    <%= @cfg_sede.nombre_sede %>
  </div>
  <div class="col">
    <%= @cfg_sede.departamento %>
  </div>  
</div>

<div class="row">
  <div class="col titulos-campos">
    Municipio   
  </div>
  <div class="col titulos-campos">
    Encargado
  </div>
  <div class="col titulos-campos">
    Dirección    
  </div>
</div>
<div class="row">
  <div class="col">
    <%= @cfg_sede.municipio %>
  </div>
  <div class="col">
    <%= @cfg_sede.encargado %>
  </div>
  <div class="col">
    <%= @cfg_sede.direccion %>
  </div>  
</div>

<div class="row">
  <div class="col titulos-campos">
    Telefono1   
  </div>
  <div class="col titulos-campos">
    Telefono2
  </div>  
</div>
<div class="row">
  <div class="col">
    <%= @cfg_sede.telefono1 %>
  </div>
  <div class="col">
    <%= @cfg_sede.telefono2 %>
  </div>
</div>


<BR>
<hr>
<h4> Lista de consultorios </h4>
<a href="/cfg_empresas/<%=@cfg_empresa.id%>/cfg_sedes/<%=@cfg_sede.id%>/cfg_consultorios/new?regresar=<%=request.fullpath%>">Crear</a>
<!-- LISTA DE LOS CONSULTORIOS -->
<%= render 'cfg_consultorios/lista_consultorios', cfg_empresa: @cfg_empresa, cfg_sede: @cfg_sede %>
<br>
<hr/>
<div class="actions text-center">
    <%= link_to 'Editar', edit_cfg_empresa_cfg_sede_path(@cfg_empresa,@cfg_sede), class: "btn btn-primary" %>  
    <%= link_to 'Regresar', cfg_empresa_cfg_sedes_path, class: "btn btn-primary" %>
</div>