config/routes.rb
Rails.application.routes.draw do

  resources :cfg_opciones_menus do
    collection do
      get 'buscar'
    end
    resources :cfg_operaciones_opciones_menu
  end
  resources :cfg_perfiles_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_operaciones'
      post 'guardar_operacion_opcion'
      post 'guardar_todas_operacion_opcion'
    end
    member do
      get 'asociar_opciones_menu'
      post 'guardar_asociar_opciones_menu'
    end
  end
  resources :cfg_usuarios do
    collection do
      get 'buscar'
      post 'actualizar_sedes_por_empresa'
    end
    member do
      get 'reiniciar_clave'
      post 'guardar_reinicio_clave'
    end 
  end
  
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'my_devise/registrations'  }
  
  resources :cfg_pacientes
  resources :cfg_items_horarios
  resources :cfg_horarios do
    collection do
      post 'listar_horarios'  
      post 'editar_horarios'    
    end
  end
  resources :cfg_empresas do
    resources :cfg_sedes do
      resources :cfg_consultorios
    end    
  end

  resources :cit_turnos do
    collection do
      post 'buscar_usuario'
      post 'buscar_horarios'
      post 'buscar_agenda'
      post 'buscar_evento'      
      get 'search'
      post 'buscar'
      post 'buscar_prestador'
    end
    resources :cit_citas
  end

  resources :cfg_dias_no_laborales
  resources :citas do
    collection do
      post 'buscar_usuario'
      post 'buscar_agenda'
      post 'buscar_paciente'
      post 'cancelar_cita'
      get 'usuarios'
    end
  end
  root 'bienvenida#index'
  get 'bienvenida/index'
  resources :especialidades
  post '/cfg_empresas/:id/:activo', to: 'cfg_empresas#estatus_empresa', as: 'estatus_empresa'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:id/:activo', to: 'cfg_sedes#estatus_sede', as: 'estatus_sede'
  post '/cfg_empresas/:cfg_empresa_id/cfg_sedes/:cfg_sede_id/cfg_consultorios/:id/:activo', to: 'cfg_consultorios#estatus_consultorio', as: 'estatus_consultorio'
  post '/cfg_pacientes/buscar_pacientes', to: 'cfg_pacientes#buscar_pacientes', as: 'buscar_pacientes'
  post '/cfg_pacientes/buscar_paciente', to: 'cfg_pacientes#buscar_paciente', as: 'buscar_paciente'
  # usuarios
  post '/cfg_usuarios/:id/:activo', to: 'cfg_usuarios#estatus_usuario', as: 'estatus_usuario'
  post '/cfg_perfiles_usuarios/:id/:activo', to: 'cfg_perfiles_usuarios#estatus_perfil', as: 'estatus_perfil'
  post '/cfg_opciones_menus/:id/:activo', to: 'cfg_opciones_menus#estatus_opcion', as: 'estatus_opcion'
  post '/cfg_opciones_menu/:cfg_opciones_menu_id/cfg_operaciones_opciones_menu/:id/:activo', to: 'cfg_operaciones_opciones_menu#estatus_operacion', as: 'estatus_operacion' 
  post '/cit_citas/buscar_paciente_cita', to: 'cit_citas#buscar_paciente_cita', as: 'buscar_paciente_cita'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Errores generados por id's o recursos no existentes, entre otros
  get 'errors/not_found'
  get 'errors/internal_server_error'  
  get '*path', to: 'application#routing_error'
  # Obligatoriamente va en el último lugar. Caso contrario, devuelve cualquier request, así no tenga error
  get '*unmatched_route', to: 'errors#not_found'
end

app/controllers/cfg_perfiles_usuarios_controller.rb
class CfgPerfilesUsuariosController < ApplicationController
  before_action :set_cfg_perfiles_usuario, only: [:show, :edit, :update, :estatus_perfil, :asociar_opciones_menu, :guardar_asociar_opciones_menu] # , :actualizar_operaciones

  # GET /cfg_perfiles_usuarios
  # GET /cfg_perfiles_usuarios.json
  def index
    query_listar_perfiles
  end

  # Buscar usuarios segun la ventana de criterios de busqueda
  # Y la paginacion, despues de haber filtrado por algun criterio 
  # de busqueda
  def buscar
    # Ejecuta el query
    query_listar_perfiles
    # Si la accion es buscar por los criterios de busqueda, va al js
    # De lo contrario va al index    
    if !params[:commit].nil? and params[:commit].strip == "Buscar"
      render "buscar.js"
    else
      render :index
    end  
  end

  def query_listar_perfiles
    # Variables para la condicion y valores del query
    condiciones = []
    argumentos = Hash.new 
 
    # Criterio de busqueda: nombre 
    unless params[:nombre].blank?
      condiciones << 'compara_ascii(UPPER(nombre_perfil)) ILIKE compara_ascii(UPPER(:nombre))'
      argumentos[:nombre] = "%"+params[:nombre].strip+"%"
    end
    # Criterio de búsqueda: activo
    unless params[:activo].blank?
      condiciones << 'activo = :activo'
      argumentos[:activo] = params[:activo]
    end
    # Criterio de búsqueda: asociado a empresa
    unless params[:asociado_empresa].blank?
      condiciones << 'asociado_empresa = :asociado_empresa'
      argumentos[:asociado_empresa] = params[:asociado_empresa]
    end

    # Query
    @cfg_perfiles_usuarios = CfgPerfilesUsuario.select("id, UPPER(nombre_perfil) as nombre_perfil, activo, asociado_empresa, observaciones")   
    .order('nombre_perfil').page(params[:page])
    .where(condiciones.join(" AND "),argumentos)

  end

  # GET /cfg_perfiles_usuarios/1
  # GET /cfg_perfiles_usuarios/1.json
  def show
    @readonly = true
  end

  # GET /cfg_perfiles_usuarios/new
  def new
    @cfg_perfiles_usuario = CfgPerfilesUsuario.new
  end

  # POST /cfg_perfiles_usuarios
  # POST /cfg_perfiles_usuarios.json
  def create
    begin
      @cfg_perfiles_usuario = CfgPerfilesUsuario.new(cfg_perfiles_usuario_params)  
      @cfg_perfiles_usuario.save!
      # Redireccionar al consultar empresa
      redirect_to @cfg_perfiles_usuario, notice: 'El perfil de usuario fue creado satisfactoriamente'               
    rescue ActiveRecord::RecordInvalid =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar el perfil de usuario"
      render :new
    rescue ActiveRecord::RecordNotUnique =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar el perfil de usuario - id no es único"
      render :new  
    rescue => exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar el perfil de usuario"
      render :new
    end
  end

  # GET /cfg_perfiles_usuarios/1/edit
  def edit
  end

  # PATCH/PUT /cfg_perfiles_usuarios/1
  # PATCH/PUT /cfg_perfiles_usuarios/1.json
  def update
    begin
      # Actualizar información del perfil del usuario
      @cfg_perfiles_usuario.update_attributes!(cfg_perfiles_usuario_params)
      # Redireccionar al consultar 
      redirect_to @cfg_perfiles_usuario, notice: 'El perfil de usuario fue actualizado satisfactoriamente'         
    rescue ActiveRecord::RecordInvalid =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar el perfil de usuario - registro inválido"
      render :edit
    rescue ActiveRecord::RecordNotUnique =>  exception
      imprimir_mensajes_excepcion(exception)
      flash[:alert] = "Error al guardar el perfil de usuario - id no es único"
      render :edit    
    rescue => exception
      imprimir_mensajes_excepcion(exception)
      render :edit      
    end
  end

  # METODO QUE ACTUALIZA EL ESTATUS ACTIVO DEL PERFIL
  def estatus_perfil
    if @cfg_perfiles_usuario.update(activo: !devolver_valor_activo(params[:activo]))
      flash[:notice] = "Estatus del perfil de usuario fue actualizado satisfactoriamente"      
    else
      flash[:alert] = "Estatus del perfil de usuario no pudo ser actualizado"  
      # Mostrar junto al mensaje de alert, los errores del modelo
      @cfg_perfiles_usuario.errors.each do |campo,msg| 
        flash[:alert] = flash[:alert]  + "<BR>"
        flash[:alert] = flash[:alert]  + msg 
      end
    end
    redirect_to cfg_perfiles_usuarios_url  
  end 
 
  def asociar_opciones_menu
    @opcion_id = nil
    @perfil_id = ""
    @nombre_perfil = ""
    @nombre_opcion = ""
    @opciones_marcadas_perfil = Array.new
    opciones_marcadas_perfil = CfgOpcionesMenuPerfilUsuario.select("cfg_opciones_menu_id")
      .where("cfg_perfiles_usuario_id = ?", @cfg_perfiles_usuario.id)
    if !opciones_marcadas_perfil.nil?  and opciones_marcadas_perfil.size > 0
      opciones_marcadas_perfil.each do |opcion|
        @opciones_marcadas_perfil << opcion.cfg_opciones_menu_id
      end
    end
  end

  def guardar_asociar_opciones_menu
    guardo = 0
    flash[:alert] = ""
    #"opcion_id"=>"29", "marcado"=>"0"
    opcion_id = params[:opcion_id]
    marcado   = params[:marcado]
    begin
    CfgOpcionesMenuPerfilUsuario.transaction do
    registro = CfgOpcionesMenuPerfilUsuario.find_by("cfg_perfiles_usuario_id = ? AND cfg_opciones_menu_id = ?",
      @cfg_perfiles_usuario.id, opcion_id)
    if registro.nil? # No existe 
      if marcado == "0"    # No se realiza ningun cambio en bd
      elsif marcado == "1" # Se debe crear en la tabla
         cfg = CfgOpcionesMenuPerfilUsuario.new
         cfg.cfg_perfiles_usuario_id = @cfg_perfiles_usuario.id
         cfg.cfg_opciones_menu_id = opcion_id
         cfg.save!
         guardo = 1
         @mensaje  = "La opción de menú fue asociada satisfactoriamente"
         # Buscar el id de la opcion superior de opcion_id
         opcion_sup1 = CfgOpcionesMenu.find(opcion_id)
         if !opcion_sup1.nil?
          puts "Opcion superior id: ", opcion_sup1.id_opcion_padre
          # Crear la opcion superior para que aparezca en el menu,
          # si ya no esta registrada para el perfil
          cfg_opc_menusup_perfil = CfgOpcionesMenuPerfilUsuario.find_by("cfg_perfiles_usuario_id = ? AND cfg_opciones_menu_id = ?",
          @cfg_perfiles_usuario.id, opcion_sup1.id_opcion_padre)
          if cfg_opc_menusup_perfil.nil?
            puts "No esta registrado el superior...."
            cfg2 = CfgOpcionesMenuPerfilUsuario.new
            cfg2.cfg_perfiles_usuario_id = @cfg_perfiles_usuario.id
            cfg2.cfg_opciones_menu_id = opcion_sup1.id_opcion_padre
            cfg2.save!
            # Buscar el id de la opcion padre de la opcion superior
            opcion_sup2 = CfgOpcionesMenu.find(opcion_sup1.id_opcion_padre)
            if !opcion_sup2.nil?
              puts "Opcion superior2 id: ", opcion_sup2.id_opcion_padre
              # Crear la opcion superior para que aparezca en el menu,
              # si ya no esta registrada para el perfil
              cfg_opc_menusup_perfil2 = CfgOpcionesMenuPerfilUsuario.find_by("cfg_perfiles_usuario_id = ? AND cfg_opciones_menu_id = ?",
              @cfg_perfiles_usuario.id, opcion_sup2.id_opcion_padre)
              if cfg_opc_menusup_perfil2.nil?
                puts "No esta registrado el padre...."
                cfg3 = CfgOpcionesMenuPerfilUsuario.new
                cfg3.cfg_perfiles_usuario_id = @cfg_perfiles_usuario.id
                cfg3.cfg_opciones_menu_id = opcion_sup2.id_opcion_padre
                cfg3.save!
              else
                puts "Si esta registrado el padre...."
              end    
            end
          else
            puts "Si esta registrado el superior...."
          end  
          
         end
      end          
    else # Si existe el registro
      if marcado == "0"    # Se debe eliminar de la tabla
         registro.destroy
         @mensaje = "La opción de menú fue eliminada satisfactoriamente"
         # Buscar la opcion superior de opcion_id para removerla
         # en caso que no tenga opciones hijas asociadas al perfil
         opcion_sup1 = CfgOpcionesMenu.find(opcion_id)
         if !opcion_sup1.nil?
          puts "Opcion superior id: ", opcion_sup1.id_opcion_padre
          # Buscar las opciones hijas en el perfil
          opciones_superior = CfgOpcionesMenuPerfilUsuario.select("cfg_opciones_menu.id").
            left_outer_joins(:cfg_opciones_menu).
            where("cfg_perfiles_usuario_id = ? AND cfg_opciones_menu.id_opcion_padre = ? AND cfg_opciones_menu.activo IS TRUE", 
              @cfg_perfiles_usuario.id, opcion_sup1.id_opcion_padre)
          if opciones_superior.size == 0 # No tiene opciones más opciones asociadas al perfil, se elimina
            registro1 = CfgOpcionesMenuPerfilUsuario.find_by("cfg_perfiles_usuario_id = ? AND cfg_opciones_menu_id = ?",
              @cfg_perfiles_usuario.id, opcion_sup1.id_opcion_padre)
            registro1.destroy
            # Buscar la opcion superior de opcion_sup1.id_opcion_padre para removerla
            # en caso que no tenga opciones hijas asociadas al perfil
            opcion_sup2 = CfgOpcionesMenu.find(opcion_sup1.id_opcion_padre)
            if !opcion_sup2.nil?
              puts "Opcion superior id: ", opcion_sup2.id_opcion_padre
              # Buscar las opciones hijas en el perfil
              opciones_superior2 = CfgOpcionesMenuPerfilUsuario.select("cfg_opciones_menu.id").
                left_outer_joins(:cfg_opciones_menu).
                where("cfg_perfiles_usuario_id = ? AND cfg_opciones_menu.id_opcion_padre = ? AND cfg_opciones_menu.activo IS TRUE", 
                  @cfg_perfiles_usuario.id, opcion_sup2.id_opcion_padre)
              if opciones_superior2.size == 0 # No tiene opciones más opciones asociadas al perfil, se elimina

app/helpers/cfg_perfiles_usuarios_helper.rb
module CfgPerfilesUsuariosHelper
	def obtener_opciones_padre_menu_activas
      CfgOpcionesMenu.select("id, UPPER(nombre_opcion) AS nombre_opcion, id_opcion_padre")
      .where("activo IS TRUE AND id_opcion_padre = ? AND id <> ?", 0, 0)
      .order("id ASC") #orden  #nombre_opcion
  end 

  def obtener_subopciones_activas(id_opcion_padre)
      CfgOpcionesMenu.select("id, UPPER(nombre_opcion) AS nombre_opcion, id_opcion_padre")
      .where("activo IS TRUE AND id_opcion_padre = ? ", id_opcion_padre)
      .order("id ASC") #nombre_opcion #nombre_opcion
  end 

  def operaciones_segun_opcion(opcion_id)
      CfgOperacionesOpcionesMenu.select("id, operacion")
      .where("activo IS TRUE AND cfg_opciones_menu_id = ? ", opcion_id) 
      .order("operacion")
  end

  def opciones_menu_perfil(perfil_id)
    html = ""
      
        # Obtener las opciones padre del menú segun el perfil
        # NIVEL 0       
        opciones_padre_perfil = obtener_opciones_menu_segun_perfil_opcion_padre(perfil_id, 0)          
        # Recorrer las opciones del menu padre e hijas segun el perfil
        if !opciones_padre_perfil.nil? and opciones_padre_perfil.size > 0     
          opciones_padre_perfil.each do |opcion_padre|            
            # Obtener las opciones por cada menu
            # NIVEL 1
            opciones = obtener_opciones_menu_segun_perfil_opcion_padre(perfil_id, opcion_padre.id)
             if !opciones.nil? and opciones.size > 0 
                # Mostrar la opcion padre
                html = html + "<b>" + opcion_padre.nombre_opcion.upcase + "</b>" 
                html = html + "<BR/>"               
                html = html + "<ul>"
                # Recorrer las opciones
                opciones.each do |opcion|                          
                  html = html + "<li>" +  opcion.nombre_opcion.upcase + "</li>" 
                  #html = html + "<BR/>"
                  # Buscar las sub-opciones
                  # NIVEL 2
                  sub_opciones = obtener_opciones_menu_segun_perfil_opcion_padre(perfil_id, opcion.id)
                  if !sub_opciones.nil? 
                    if sub_opciones.size > 0
                      # Mostrar la opcion con submenu
                      sub_opciones.each do |sub_opcion|
                        html = html + "        - " +  sub_opcion.nombre_opcion.upcase              
                        html = html + "<BR/>"
                      end  
                    end                      
                  end                   
                end   # end del each opciones
                html = html + "</ul>"
             end   
          end  # end del each opciones_padre
        end # end del if opciones_padre          
    return html      
  end

  def operaciones_segun_opcion_texto(perfil_id, opcion_id)      
      puts "helper - operaciones_segun_opcion_texto... "
      puts perfil_id
      puts opcion_id
      operaciones = CfgOperacionesPerfil.select("operacion")
                    .joins("JOIN cfg_operaciones_opciones_menu ON cfg_operaciones_perfiles.cfg_operaciones_opciones_menu_id = cfg_operaciones_opciones_menu.id")  
                    .where("cfg_perfiles_usuario_id = ? AND cfg_opciones_menu_id = ? ", perfil_id, opcion_id) 
                    .order("operacion")
      if operaciones.size > 0
        texto_operaciones = "("
        operaciones.each do |o|
          if texto_operaciones == "("
            texto_operaciones = texto_operaciones + o.operacion
          else
            texto_operaciones = texto_operaciones + ", " +  o.operacion
          end          
        end              
        texto_operaciones = texto_operaciones + ")" 
      end  
      return texto_operaciones
  end


end

app/views/cfg_perfiles_usuarios/_lista_perfiles.html.erb
<% if !@cfg_perfiles_usuarios.nil? and @cfg_perfiles_usuarios.size > 0 %>
  <table class="table table-bordered table-hover table-striped"><!--  table-responsive-->
  	<thead>
	    <tr>
	      <th>Nombre</th>
	      <th>¿Activo?</th>
	      <th>¿Asociado empresa?</th>
	      <th colspan="4">Operaciones</th>
	    </tr>
	</thead>
	<tbody>
	    <% @cfg_perfiles_usuarios.each do |cfg_perfil_usuario| %>
	      <tr>
	        <td><%= cfg_perfil_usuario.nombre_perfil %></td>
	        <td><%= cfg_perfil_usuario.estatus?(cfg_perfil_usuario.activo) %></td>
	        <td><%= cfg_perfil_usuario.estatus?(cfg_perfil_usuario.asociado_empresa) %></td>
	        <td align="center">	        	
	        	<%= link_to(cfg_perfil_usuario) do %>  					
  					<span class="oi oi-magnifying-glass" title="Consultar" aria-hidden="true"></span>
				<% end %>	
	        </td>
	        <td align="center">	        	
	        	<%= link_to(edit_cfg_perfiles_usuario_path(cfg_perfil_usuario)) do %>
  					<span class="oi oi-pencil" title="Editar" aria-hidden="true"></span>	
				<% end %>
	        </td>
	        <td align="center">
	        	<%= link_to(estatus_perfil_path(cfg_perfil_usuario, devolver_valor_activo(cfg_perfil_usuario.activo)), method: :post,data: { confirm: '¿Está seguro que desea activar/inactivar el perfil de usuario?' }) do %>	        	
	        	     <%= mostrar_operacion_activar(cfg_perfil_usuario.activo).html_safe  %>
	        	<% end %>	
	        </td>
	        <td align="center">
				<%= link_to(asociar_opciones_menu_cfg_perfiles_usuario_path(cfg_perfil_usuario)) do %>				  
				  <span class="oi oi-list" title="Asociar Opciones de Menú" aria-hidden="true"></span>
				<% end %>
	        </td>
	      </tr>
	    <% end %>
	</tbody>
  </table>	
<% else %>
  <div class="sin_registros"> No existen perfiles registrados </div> 
<% end %>  

app/views/cfg_perfiles_usuarios/asociar_opciones_menu.html (copia).erb
<script>
  $(document).ready(
    function(){    
      // Evento 
      $("input[type=checkbox]").change(function() {
        var marcado = "0"
        if ($(this).is(':checked')) {
          marcado = "1";
        }
        $.ajax({
          url: "/cfg_perfiles_usuarios/<%=@cfg_perfiles_usuario.id%>/guardar_asociar_opciones_menu",
          type: "POST",
          data: { opcion_id: $(this).val(),
                  marcado: marcado
                },
          success: function(resp){

          }
        }); 
      }); 
    }    
  );
</script>
<h2>Asociar Opciones de Menú al Perfil de Usuario</h2>
<br/>
<h4>Perfil de Usuario</h4>
<hr/>
<div class="row">
  <div class="col titulos-campos">     
    Nombre
  </div>
  <div class="col titulos-campos">     
    ¿Activo?
  </div>
  <div class="col titulos-campos">     
    ¿Asociado a Empresa?
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_perfiles_usuario.nombre_perfil %>&nbsp;
  </div>  
  <div class="col"> 
    <%= @cfg_perfiles_usuario.estatus?(@cfg_perfiles_usuario.activo) %>&nbsp;
  </div>  
  <div class="col">  
    <%= @cfg_perfiles_usuario.estatus?(@cfg_perfiles_usuario.asociado_empresa) %>&nbsp;
  </div>
</div>  

<div class="row">
  <div class="col titulos-campos">     
    Observaciones
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_perfiles_usuario.observaciones.upcase if !@cfg_perfiles_usuario.observaciones.blank? %>&nbsp;
  </div> 
</div>  

<br/>
<h4>Opciones de Menú</h4>
<hr/>
<%= form_for(@cfg_perfiles_usuario, url: guardar_asociar_opciones_menu_cfg_perfiles_usuario_path(@cfg_perfiles_usuario), method: :post) do |form| %>

<% # Obtener las opciones padre del menú segun el perfil
  opciones_padre = obtener_opciones_padre_menu_activas 
%>
  <% if !opciones_padre.nil? and opciones_padre.size > 0 %>
      <% opciones_padre.each do |opcion_padre| %>




      
         <div class="row">         
           <div class="col">
            <div class="clase1">
              <%= check_box_tag("opciones[]",opcion_padre.id, @opciones_marcadas_perfil.include?(opcion_padre.id)  ) %>
              <%# opcion_padre.id %>  <%# opcion_padre.nombre_opcion %> 
              <% titulo = opcion_padre.id.to_s + " - " + opcion_padre.nombre_opcion  %>
              <%= link_to titulo, cfg_opciones_menu_path(opcion_padre) %>
              <br/>
            </div>  
           </div>   
         </div>
         <% # Buscar las opciones nivel 1
            opciones_nivel_1 = obtener_subopciones_activas(opcion_padre.id)
         %>
         <% opciones_nivel_1.each do |opcion_nivel_1| %>
           &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
           <%= check_box_tag("opciones[]",opcion_nivel_1.id, @opciones_marcadas_perfil.include?(opcion_nivel_1.id)  ) %> 
           <%# opcion_nivel_1.id %>  <%# opcion_nivel_1.nombre_opcion %> 
           <% titulo = opcion_nivel_1.id.to_s + " - " + opcion_nivel_1.nombre_opcion  %>
           <%= link_to titulo, cfg_opciones_menu_path(opcion_nivel_1) %>
           <br/>
           <% # Buscar las opciones nivel 2
            opciones_nivel_2 = obtener_subopciones_activas(opcion_nivel_1.id)
           %>
           <% opciones_nivel_2.each do |opcion_nivel_2| %>
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%= check_box_tag("opciones[]",opcion_nivel_2.id, @opciones_marcadas_perfil.include?(opcion_nivel_2.id)  ) %>
              <% titulo = opcion_nivel_2.id.to_s + " - " + opcion_nivel_2.nombre_opcion  %>
              <%= link_to titulo, cfg_opciones_menu_path(opcion_nivel_2) %>
              <br/>
           <% end %>
         <% end %>
      <% end %>
  <% else %>
    No existen opciones de menú registradas
  <% end %>


<br>
<hr/>
<div class="actions text-center"> 
    <%= link_to 'Regresar', cfg_perfiles_usuarios_path, class: "btn btn-primary" %>
</div>
<% end %>

app/views/cfg_perfiles_usuarios/show.html (otra copia).erb
<h2>Consultar Perfil de Usuario</h2>
<br/>
<div class="row">
  <div class="col titulos-campos">     
    Nombre
  </div>
  <div class="col titulos-campos">     
    ¿Activo?
  </div>
  <div class="col titulos-campos">     
    ¿Asociado a Empresa?
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_perfiles_usuario.nombre_perfil %>&nbsp;
  </div>  
  <div class="col"> 
    <%= @cfg_perfiles_usuario.estatus?(@cfg_perfiles_usuario.activo) %>&nbsp;
  </div>  
  <div class="col">  
    <%= @cfg_perfiles_usuario.estatus?(@cfg_perfiles_usuario.asociado_empresa) %>&nbsp;
  </div>
</div>  

<div class="row">
  <div class="col titulos-campos">     
    Observaciones
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_perfiles_usuario.observaciones.upcase if !@cfg_perfiles_usuario.observaciones.blank? %>&nbsp;
  </div> 
</div>  

<br>
<hr/>
<div class="actions text-center">
    <%= link_to 'Editar', edit_cfg_perfiles_usuario_path(@cfg_perfiles_usuario), class: "btn btn-primary" %>  
    <%= link_to 'Regresar', cfg_perfiles_usuarios_path, class: "btn btn-primary" %>
</div>

app/views/cfg_perfiles_usuarios/show.html.erb
<h2>Consultar Perfil de Usuario</h2>
<br/>
<%= render 'form', cfg_perfiles_usuario: @cfg_perfiles_usuario %>



------------------------
<h2>Consultar Perfil de Usuario</h2>
<br/>
<div class="row">
  <div class="col titulos-campos">     
    Nombre
  </div>
  <div class="col titulos-campos">     
    ¿Activo?
  </div>
  <div class="col titulos-campos">     
    ¿Asociado a Empresa?
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_perfiles_usuario.nombre_perfil %>&nbsp;
  </div>  
  <div class="col"> 
    <%= @cfg_perfiles_usuario.estatus?(@cfg_perfiles_usuario.activo) %>&nbsp;
  </div>  
  <div class="col">  
    <%= @cfg_perfiles_usuario.estatus?(@cfg_perfiles_usuario.asociado_empresa) %>&nbsp;
  </div>
</div>  

<div class="row">
  <div class="col titulos-campos">     
    Observaciones
  </div>
</div>  
<div class="row">
  <div class="col">     
    <%= @cfg_perfiles_usuario.observaciones.upcase if !@cfg_perfiles_usuario.observaciones.blank? %>&nbsp;
  </div> 
</div>  

<br>
<hr/>
<div class="actions text-center">
    <%= link_to 'Editar', edit_cfg_perfiles_usuario_path(@cfg_perfiles_usuario), class: "btn btn-primary" %>  
    <%= link_to 'Regresar', cfg_perfiles_usuarios_path, class: "btn btn-primary" %>
</div>